"""initial_canonical_schema

Revision ID: aa4ad2c46b33
Revises: None
Create Date: 2026-07-22 14:54:17.413114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4ad2c46b33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('alias_name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliases_alias_name'), 'aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_aliases_entity_id'), 'aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_aliases_entity_type'), 'aliases', ['entity_type'], unique=False)
    op.create_index(op.f('ix_aliases_id'), 'aliases', ['id'], unique=False)
    op.create_index('ix_aliases_type_name', 'aliases', ['entity_type', 'alias_name'], unique=False)
    op.create_table('authors',
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_full_name'), 'authors', ['full_name'], unique=False)
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_normalized_name'), 'authors', ['normalized_name'], unique=True)
    op.create_table('genres',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_table('import_jobs',
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_id'), 'import_jobs', ['id'], unique=False)
    op.create_table('members',
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_display_name'), 'members', ['display_name'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_normalized_name'), 'members', ['normalized_name'], unique=True)
    op.create_table('publishers',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_id'), 'publishers', ['id'], unique=False)
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=True)
    op.create_table('series',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_title'), 'series', ['title'], unique=True)
    op.create_table('sources',
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('meetup_number', sa.Integer(), nullable=True),
    sa.Column('pdf_page', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('importer_name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_file_meetup', 'sources', ['file_path', 'meetup_number'], unique=False)
    op.create_index(op.f('ix_sources_file_path'), 'sources', ['file_path'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_meetup_number'), 'sources', ['meetup_number'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('venues',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_is_online'), 'venues', ['is_online'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=True)
    op.create_table('canonical_books',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('normalized_title', sa.String(length=512), nullable=False),
    sa.Column('subtitle', sa.String(length=512), nullable=True),
    sa.Column('sort_title', sa.String(length=512), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('publisher_id', sa.String(length=36), nullable=True),
    sa.Column('series_id', sa.String(length=36), nullable=True),
    sa.Column('isbn10', sa.String(length=10), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goodreads_id', sa.String(length=64), nullable=True),
    sa.Column('openlibrary_id', sa.String(length=64), nullable=True),
    sa.Column('google_books_id', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_books_author_id'), 'canonical_books', ['author_id'], unique=False)
    op.create_index(op.f('ix_canonical_books_goodreads_id'), 'canonical_books', ['goodreads_id'], unique=False)
    op.create_index(op.f('ix_canonical_books_id'), 'canonical_books', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_books_isbn10'), 'canonical_books', ['isbn10'], unique=False)
    op.create_index(op.f('ix_canonical_books_isbn13'), 'canonical_books', ['isbn13'], unique=False)
    op.create_index('ix_canonical_books_norm_author', 'canonical_books', ['normalized_title', 'author_id'], unique=False)
    op.create_index(op.f('ix_canonical_books_normalized_title'), 'canonical_books', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_canonical_books_title'), 'canonical_books', ['title'], unique=False)
    op.create_table('import_logs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('log_level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_id'), 'import_logs', ['id'], unique=False)
    op.create_index(op.f('ix_import_logs_job_id'), 'import_logs', ['job_id'], unique=False)
    op.create_table('meetups',
    sa.Column('meetup_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('venue_id', sa.String(length=36), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('attendance_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetups_date'), 'meetups', ['date'], unique=False)
    op.create_index(op.f('ix_meetups_id'), 'meetups', ['id'], unique=False)
    op.create_index(op.f('ix_meetups_meetup_number'), 'meetups', ['meetup_number'], unique=True)
    op.create_index(op.f('ix_meetups_source_id'), 'meetups', ['source_id'], unique=False)
    op.create_index(op.f('ix_meetups_venue_id'), 'meetups', ['venue_id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_errors_id'), 'validation_errors', ['id'], unique=False)
    op.create_index(op.f('ix_validation_errors_job_id'), 'validation_errors', ['job_id'], unique=False)
    op.create_table('book_relations',
    sa.Column('source_book_id', sa.String(length=36), nullable=False),
    sa.Column('target_book_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_book_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['target_book_id'], ['canonical_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_relations_id'), 'book_relations', ['id'], unique=False)
    op.create_index(op.f('ix_book_relations_source_book_id'), 'book_relations', ['source_book_id'], unique=False)
    op.create_index(op.f('ix_book_relations_target_book_id'), 'book_relations', ['target_book_id'], unique=False)
    op.create_table('current_reads',
    sa.Column('meetup_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_book_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_book_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_reads_canonical_book_id'), 'current_reads', ['canonical_book_id'], unique=False)
    op.create_index(op.f('ix_current_reads_id'), 'current_reads', ['id'], unique=False)
    op.create_index(op.f('ix_current_reads_meetup_id'), 'current_reads', ['meetup_id'], unique=False)
    op.create_index(op.f('ix_current_reads_member_id'), 'current_reads', ['member_id'], unique=False)
    op.create_table('discussions',
    sa.Column('meetup_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_book_id', sa.String(length=36), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_book_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_canonical_book_id'), 'discussions', ['canonical_book_id'], unique=False)
    op.create_index(op.f('ix_discussions_id'), 'discussions', ['id'], unique=False)
    op.create_index(op.f('ix_discussions_meetup_id'), 'discussions', ['meetup_id'], unique=False)
    op.create_index(op.f('ix_discussions_member_id'), 'discussions', ['member_id'], unique=False)
    op.create_index(op.f('ix_discussions_source_id'), 'discussions', ['source_id'], unique=False)
    op.create_table('imported_books',
    sa.Column('raw_title', sa.String(length=512), nullable=False),
    sa.Column('raw_author', sa.String(length=256), nullable=True),
    sa.Column('normalized_title', sa.String(length=512), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_book_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_book_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_books_canonical_book_id'), 'imported_books', ['canonical_book_id'], unique=False)
    op.create_index(op.f('ix_imported_books_id'), 'imported_books', ['id'], unique=False)
    op.create_index(op.f('ix_imported_books_normalized_title'), 'imported_books', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_imported_books_raw_author'), 'imported_books', ['raw_author'], unique=False)
    op.create_index(op.f('ix_imported_books_raw_title'), 'imported_books', ['raw_title'], unique=False)
    op.create_index(op.f('ix_imported_books_source_id'), 'imported_books', ['source_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('meetup_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_book_id', sa.String(length=36), nullable=False),
    sa.Column('recommender_id', sa.String(length=36), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_book_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.ForeignKeyConstraint(['recommender_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_canonical_book_id'), 'recommendations', ['canonical_book_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_meetup_id'), 'recommendations', ['meetup_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommender_id'), 'recommendations', ['recommender_id'], unique=False)
    op.create_table('resources',
    sa.Column('meetup_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_meetup_id'), 'resources', ['meetup_id'], unique=False)
    op.create_table('book_mentions',
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_book_id', sa.String(length=36), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_book_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_mentions_canonical_book_id'), 'book_mentions', ['canonical_book_id'], unique=False)
    op.create_index(op.f('ix_book_mentions_discussion_id'), 'book_mentions', ['discussion_id'], unique=False)
    op.create_index(op.f('ix_book_mentions_id'), 'book_mentions', ['id'], unique=False)
    op.create_table('discussion_participants',
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_participants_discussion_id'), 'discussion_participants', ['discussion_id'], unique=False)
    op.create_index(op.f('ix_discussion_participants_id'), 'discussion_participants', ['id'], unique=False)
    op.create_index(op.f('ix_discussion_participants_member_id'), 'discussion_participants', ['member_id'], unique=False)
    op.create_table('possible_duplicates',
    sa.Column('imported_book_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_canonical_id', sa.String(length=36), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_canonical_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['imported_book_id'], ['imported_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_possible_duplicates_candidate_canonical_id'), 'possible_duplicates', ['candidate_canonical_id'], unique=False)
    op.create_index(op.f('ix_possible_duplicates_id'), 'possible_duplicates', ['id'], unique=False)
    op.create_index(op.f('ix_possible_duplicates_imported_book_id'), 'possible_duplicates', ['imported_book_id'], unique=False)
    op.create_index(op.f('ix_possible_duplicates_status'), 'possible_duplicates', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('discussion_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_book_id', sa.String(length=36), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_book_id'], ['canonical_books.id'], ),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_canonical_book_id'), 'quotes', ['canonical_book_id'], unique=False)
    op.create_index(op.f('ix_quotes_discussion_id'), 'quotes', ['discussion_id'], unique=False)
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_discussion_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_canonical_book_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_possible_duplicates_status'), table_name='possible_duplicates')
    op.drop_index(op.f('ix_possible_duplicates_imported_book_id'), table_name='possible_duplicates')
    op.drop_index(op.f('ix_possible_duplicates_id'), table_name='possible_duplicates')
    op.drop_index(op.f('ix_possible_duplicates_candidate_canonical_id'), table_name='possible_duplicates')
    op.drop_table('possible_duplicates')
    op.drop_index(op.f('ix_discussion_participants_member_id'), table_name='discussion_participants')
    op.drop_index(op.f('ix_discussion_participants_id'), table_name='discussion_participants')
    op.drop_index(op.f('ix_discussion_participants_discussion_id'), table_name='discussion_participants')
    op.drop_table('discussion_participants')
    op.drop_index(op.f('ix_book_mentions_id'), table_name='book_mentions')
    op.drop_index(op.f('ix_book_mentions_discussion_id'), table_name='book_mentions')
    op.drop_index(op.f('ix_book_mentions_canonical_book_id'), table_name='book_mentions')
    op.drop_table('book_mentions')
    op.drop_index(op.f('ix_resources_meetup_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_recommendations_recommender_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_meetup_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_canonical_book_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_imported_books_source_id'), table_name='imported_books')
    op.drop_index(op.f('ix_imported_books_raw_title'), table_name='imported_books')
    op.drop_index(op.f('ix_imported_books_raw_author'), table_name='imported_books')
    op.drop_index(op.f('ix_imported_books_normalized_title'), table_name='imported_books')
    op.drop_index(op.f('ix_imported_books_id'), table_name='imported_books')
    op.drop_index(op.f('ix_imported_books_canonical_book_id'), table_name='imported_books')
    op.drop_table('imported_books')
    op.drop_index(op.f('ix_discussions_source_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_member_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_meetup_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_canonical_book_id'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_current_reads_member_id'), table_name='current_reads')
    op.drop_index(op.f('ix_current_reads_meetup_id'), table_name='current_reads')
    op.drop_index(op.f('ix_current_reads_id'), table_name='current_reads')
    op.drop_index(op.f('ix_current_reads_canonical_book_id'), table_name='current_reads')
    op.drop_table('current_reads')
    op.drop_index(op.f('ix_book_relations_target_book_id'), table_name='book_relations')
    op.drop_index(op.f('ix_book_relations_source_book_id'), table_name='book_relations')
    op.drop_index(op.f('ix_book_relations_id'), table_name='book_relations')
    op.drop_table('book_relations')
    op.drop_index(op.f('ix_validation_errors_job_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_id'), table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_meetups_venue_id'), table_name='meetups')
    op.drop_index(op.f('ix_meetups_source_id'), table_name='meetups')
    op.drop_index(op.f('ix_meetups_meetup_number'), table_name='meetups')
    op.drop_index(op.f('ix_meetups_id'), table_name='meetups')
    op.drop_index(op.f('ix_meetups_date'), table_name='meetups')
    op.drop_table('meetups')
    op.drop_index(op.f('ix_import_logs_job_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_id'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_canonical_books_title'), table_name='canonical_books')
    op.drop_index(op.f('ix_canonical_books_normalized_title'), table_name='canonical_books')
    op.drop_index('ix_canonical_books_norm_author', table_name='canonical_books')
    op.drop_index(op.f('ix_canonical_books_isbn13'), table_name='canonical_books')
    op.drop_index(op.f('ix_canonical_books_isbn10'), table_name='canonical_books')
    op.drop_index(op.f('ix_canonical_books_id'), table_name='canonical_books')
    op.drop_index(op.f('ix_canonical_books_goodreads_id'), table_name='canonical_books')
    op.drop_index(op.f('ix_canonical_books_author_id'), table_name='canonical_books')
    op.drop_table('canonical_books')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_is_online'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_meetup_number'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_file_path'), table_name='sources')
    op.drop_index('ix_sources_file_meetup', table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_series_title'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_id'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_members_normalized_name'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_members_display_name'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_import_jobs_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_authors_normalized_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_full_name'), table_name='authors')
    op.drop_table('authors')
    op.drop_index('ix_aliases_type_name', table_name='aliases')
    op.drop_index(op.f('ix_aliases_id'), table_name='aliases')
    op.drop_index(op.f('ix_aliases_entity_type'), table_name='aliases')
    op.drop_index(op.f('ix_aliases_entity_id'), table_name='aliases')
    op.drop_index(op.f('ix_aliases_alias_name'), table_name='aliases')
    op.drop_table('aliases')
    # ### end Alembic commands ###
